### ISSUE TITLE
Package build week 20220926 - 20220930

### ISSUE THREAD

**Issue by orensbruli** [open-rmf/rmf_deployment_template#22]

**Comment by orensbruli** [comment]
# 2022 09 29
## Rolling
### Failing
https://build.ros2.org/job/Rbin_uJ64__rmf_traffic_ros2__ubuntu_jammy_amd64__binary
https://build.ros2.org/job/Rbin_uJ64__rmf_traffic_examples__ubuntu_jammy_amd64__binary/
https://build.ros2.org/job/Rbin_uJ64__rmf_task_sequence__ubuntu_jammy_amd64__binary/
https://build.ros2.org/job/Rbin_uJ64__rmf_obstacle_msgs__ubuntu_jammy_amd64__binary/
https://build.ros2.org/job/Rbin_uJ64__rmf_demos_maps__ubuntu_jammy_amd64__binary/
https://build.ros2.org/job/Rbin_uJ64__pybind11_json_vendor__ubuntu_jammy_amd64__binary/

### Need to be released
rmf_building_sim_gz_classic_plugins
rmf_building_sim_gz_plugins

rmf_demos_bridges
rmf_demos_fleet_adapter
rmf_demos_gz_classic

rmf_robot_sim_gz_classic_plugins
rmf_robot_sim_gz_plugins

rmf_visualization_floorplans
rmf_visualization_navgraphs
rmf_visualization_obstacles

**Comment by orensbruli** [comment]
# 2022 09 30

Checking errors in https://build.ros2.org/job/Rbin_uJ64__rmf_websocket__ubuntu_jammy_amd64__binary/1/console
```
02:12:08 CMake Error at /opt/ros/rolling/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorTargets.cmake:74 (message):
02:12:08   The imported target "nlohmann_json_schema_validator" references the file
02:12:08 
02:12:08      "/tmp/binarydeb/ros-rolling-nlohmann-json-schema-validator-vendor-0.1.0/obj-x86_64-linux-gnu/nlohmann_json_schema_validator/lib/libnlohmann_json_schema_validator.so.2.1.0"
02:12:08 
02:12:08   but this file does not exist.  Possible reasons include:
02:12:08 
02:12:08   * The file was deleted, renamed, or moved to another location.
02:12:08 
02:12:08   * An install or uninstall procedure did not complete successfully.
02:12:08 
02:12:08   * The installation package was faulty and contained
02:12:08 
02:12:08      "/opt/ros/rolling/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorTargets.cmake"
02:12:08 
02:12:08   but not all the files it references.
02:12:08 
02:12:08 Call Stack (most recent call first):
02:12:08   /opt/ros/rolling/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorConfig.cmake:12 (include)
02:12:08   /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
02:12:08   /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/nlohmann_json_schema_validator_vendorConfig.cmake:41 (include)
02:12:08   CMakeLists.txt:21 (find_package)
02:12:08 
02:12:08 
02:12:08 -- Configuring incomplete, errors occurred!
```
It's probably some problem with the nlohmann_json_schema package installation.

PR with possible fix: https://github.com/open-rmf/nlohmann_json_schema_validator_vendor/pull/7

**Comment by orensbruli** [comment]
## 2022 10 02

```mermaid
graph TD;
  rmf_visualization_schedule --> rmf_traffic_ros2
  rmf_traffic_ros2 --> rmf_internal_msgs_FIX
  rmf_demos_gz -->  rmf_demos_maps
  rmf_demos_maps --> rmf_demos_FIX
  rmf_visualization_rviz2 --> rmf_traffic_ros2
  rmf_visualization --> rmf_visualization_rviz2
  rmf_task_ros2 --> rmf_traffic_ros2
  rmf_fleet_adapter_python --> pybind11_json_vendor
  pybind11_json_vendor --> nlohmann_json_schema_validator_vendor_FIX
  rmf_fleet_adapter --> rmf_task_ros2
  rmf_demos --> rmf_demos_maps
  rmf_demos_gz_classic --> rmf_robot_sim_gz_classic_plugins
  rmf_robot_sim_gz_classic_plugins -> (CHANGELOGS UPDATE)

```

**Comment by orensbruli** [comment]
# 2022 10 04

**Comment by orensbruli** [comment]
**Rolling | rmf_web_socket**
Investigating. **2 errors**
```
00:01:32.889 CMake Error at /opt/ros/rolling/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorTargets.cmake:74 (message):
00:01:32.890   The imported target "nlohmann_json_schema_validator" references the file
00:01:32.890 
00:01:32.890      "/tmp/binarydeb/ros-rolling-nlohmann-json-schema-validator-vendor-0.1.0/.obj-x86_64-linux-gnu/nlohmann_json_schema_validator/lib/libnlohmann_json_schema_validator.so.2.1.0"
00:01:32.890 
00:01:32.890   but this file does not exist.  Possible reasons include:
00:01:32.890 
00:01:32.890   * The file was deleted, renamed, or moved to another location.
00:01:32.890 
00:01:32.890   * An install or uninstall procedure did not complete successfully.
00:01:32.890 
00:01:32.890   * The installation package was faulty and contained
00:01:32.890 
00:01:32.890      "/opt/ros/rolling/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorTargets.cmake"
00:01:32.890 
00:01:32.890   but not all the files it references.
00:01:32.890 
00:01:32.890 Call Stack (most recent call first):
00:01:32.890   /opt/ros/rolling/lib/cmake/nlohmann_json_schema_validator/nlohmann_json_schema_validatorConfig.cmake:12 (include)
00:01:32.890   /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
00:01:32.890   /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/nlohmann_json_schema_validator_vendorConfig.cmake:41 (include)
00:01:32.890   CMakeLists.txt:21 (find_package)
00:01:32.890 
00:01:32.890 
00:01:32.890 -- Configuring incomplete, errors occurred!
```

```
00:01:32.905 /usr/lib/ccache/cc -g -O2 -ffile-prefix-map=/tmp/binarydeb/ros-rolling-rmf-websocket-2.1.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  CMakeFiles/cmTC_dc2c2.dir/src.c.o -o cmTC_dc2c2 
00:01:32.905 gmake[3]: Leaving directory '/tmp/binarydeb/ros-rolling-rmf-websocket-2.1.1/.obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
00:01:32.905 gmake[2]: Leaving directory '/tmp/binarydeb/ros-rolling-rmf-websocket-2.1.1/.obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
00:01:32.905 
00:01:32.905 
00:01:32.905 Source file was:
00:01:32.905 #include <pthread.h>
00:01:32.905 
00:01:32.905 static void* test_func(void* data)
00:01:32.905 {
00:01:32.905   return data;
00:01:32.905 }
00:01:32.905 
00:01:32.905 int main(void)
00:01:32.905 {
00:01:32.905   pthread_t thread;
00:01:32.905   pthread_create(&thread, NULL, test_func, NULL);
00:01:32.905   pthread_detach(thread);
00:01:32.905   pthread_cancel(thread);
00:01:32.905   pthread_join(thread, NULL);
00:01:32.905   pthread_atfork(NULL, NULL, NULL);
00:01:32.905   pthread_exit(NULL);
00:01:32.905 
00:01:32.905   return 0;
00:01:32.905 }
00:01:32.905 
00:01:32.905 dh_auto_configure: error: cd .obj-x86_64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_INSTALL_PREFIX=/opt/ros/rolling -DAMENT_PREFIX_PATH=/opt/ros/rolling -DCMAKE_PREFIX_PATH=/opt/ros/rolling .. returned exit code 1
00:01:32.905 make[1]: *** [debian/rules:33: override_dh_auto_configure] Error 2
00:01:32.907 make[1]: Leaving directory '/tmp/binarydeb/ros-rolling-rmf-websocket-2.1.1'
00:01:32.907 make: *** [debian/rules:27: build] Error 2
00:01:32.911 dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
00:01:32.911 E: Building failed
00:01:32.916 Traceback (most recent call last):
00:01:32.925   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 147, in build_binarydeb
00:01:32.925     subprocess.check_call(cmd, cwd=source_dir, env=env)
00:01:32.925   File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
00:01:32.925     raise CalledProcessError(retcode, cmd)
00:01:32.925 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-rolling-rmf-websocket']' returned non-zero exit status 1.
00:01:32.925 # END SUBSECTION
```

**Comment by orensbruli** [comment]
#### Rolling | rmf_visualization_schedule

Failing because of the change in the needed version of `rmf_traffic` is 2 but 3 provided.
**rmv_visualization for rolling is still waiting for release with a fix for this.**

**Comment by orensbruli** [comment]
#### **Rolling | pybind11_json_vendor **
```
CMake Error at CMakeLists.txt:29 (find_package):
00:03:10.536   By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
00:03:10.536   project has asked CMake to find a package configuration file provided by
00:03:10.536   "nlohmann_json", but CMake did not find one.
00:03:10.536 
00:03:10.536   Could not find a package configuration file provided by "nlohmann_json"
00:03:10.536   (requested version 3.2.0) with any of the following names:
00:03:10.536 
00:03:10.536     nlohmann_jsonConfig.cmake
00:03:10.536     nlohmann_json-config.cmake
00:03:10.536 
00:03:10.536   Add the installation prefix of "nlohmann_json" to CMAKE_PREFIX_PATH or set
00:03:10.536   "nlohmann_json_DIR" to a directory containing one of the above files.  If
00:03:10.536   "nlohmann_json" provides a separate development package or SDK, be sure it
00:03:10.536   has been installed.
00:03:10.536 
00:03:10.536 
00:03:10.536 -- Configuring incomplete, errors occurred!
```

**Comment by orensbruli** [comment]
#### **Rolling | rmf_demos_maps**

The source of this package has not been updated since [Feb 9, 2022 3:38 PM](https://build.ros2.org/job/Rsrc_uJ__rmf_demos_maps__ubuntu_jammy__source/1/).
Need to release rmf_demos:
- rolling
  - https://github.com/ros/rosdistro/pull/34749
- humble
  - https://github.com/ros/rosdistro/pull/34783

**Comment by orensbruli** [comment]
#### Rolling | rmf_simulation
Humble branch needed to be rested to the same point as rolling (was behind)
- rolling
  - https://github.com/ros/rosdistro/pull/34749
- humble
  - https://github.com/ros/rosdistro/pull/34783

**Comment by orensbruli** [comment]
#### Rolling |  [rmf_task_sequence ](https://build.ros2.org/job/Rbin_uJ64__rmf_task_sequence__ubuntu_jammy_amd64__binary/)

```
CMake Error at /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/ament_cmake_export_dependencies-extras.cmake:5 (find_package):
00:01:15.606   By not providing "Findament_cmake_libraries.cmake" in CMAKE_MODULE_PATH
00:01:15.606   this project has asked CMake to find a package configuration file provided
00:01:15.606   by "ament_cmake_libraries", but CMake did not find one.
00:01:15.606 
00:01:15.606   Could not find a package configuration file provided by
00:01:15.606   "ament_cmake_libraries" with any of the following names:
00:01:15.606 
00:01:15.606     ament_cmake_librariesConfig.cmake
00:01:15.606     ament_cmake_libraries-config.cmake
00:01:15.606 
00:01:15.606   Add the installation prefix of "ament_cmake_libraries" to CMAKE_PREFIX_PATH
00:01:15.606   or set "ament_cmake_libraries_DIR" to a directory containing one of the
00:01:15.606   above files.  If "ament_cmake_libraries" provides a separate development
00:01:15.606   package or SDK, be sure it has been installed.
00:01:15.606 Call Stack (most recent call first):
00:01:15.606   /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/nlohmann_json_schema_validator_vendorConfig.cmake:41 (include)
00:01:15.606   CMakeLists.txt:26 (find_package)
00:01:15.606 
00:01:15.606 
00:01:15.606 -- Configuring incomplete, errors occurred!
```

**Comment by orensbruli** [comment]
#### Rolling | nlohmann_json_schema_validator_vendor

Several packages depending on nlohmann_json_schema_validator are failing with:
```
00:01:15.601 CMake Error at /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/ament_cmake_export_dependencies-extras.cmake:5 (find_package):
00:01:15.606   By not providing "Findament_cmake_libraries.cmake" in CMAKE_MODULE_PATH
00:01:15.606   this project has asked CMake to find a package configuration file provided
00:01:15.606   by "ament_cmake_libraries", but CMake did not find one.
00:01:15.606 
00:01:15.606   Could not find a package configuration file provided by
00:01:15.606   "ament_cmake_libraries" with any of the following names:
00:01:15.606 
00:01:15.606     ament_cmake_librariesConfig.cmake
00:01:15.606     ament_cmake_libraries-config.cmake
00:01:15.606 
00:01:15.606   Add the installation prefix of "ament_cmake_libraries" to CMAKE_PREFIX_PATH
00:01:15.606   or set "ament_cmake_libraries_DIR" to a directory containing one of the
00:01:15.606   above files.  If "ament_cmake_libraries" provides a separate development
00:01:15.606   package or SDK, be sure it has been installed.
00:01:15.606 Call Stack (most recent call first):
00:01:15.606   /opt/ros/rolling/share/nlohmann_json_schema_validator_vendor/cmake/nlohmann_json_schema_validator_vendorConfig.cmake:41 (include)
00:01:15.606   CMakeLists.txt:26 (find_package)
00:01:15.606 
00:01:15.606 
00:01:15.606 -- Configuring incomplete, errors occurred!
```

Trying to fix with b3bbc750372cf520a3724c300ea54f11cdc1af01

- 0.1.1 for rolling
  - https://github.com/ros/rosdistro/pull/34784
- 0.1.1 for humble
  - https://github.com/ros/rosdistro/pull/34785

**Comment by orensbruli** [comment]
#### Rolling | rmf_api_msgs
Fixed https://github.com/ros/rosdistro/pull/34752#pullrequestreview-1129222846

**Comment by orensbruli** [comment]
Need to recheck status of `rmf_ros2`

**Comment by orensbruli** [comment]
## 2022 10 05

### Failing
[nlohmann_json_schema_validator_vendor ![Build Status](https://build.ros2.org/job/Rbin_uJ64__nlohmann_json_schema_validator_vendor__ubuntu_jammy_amd64__binary/9/badge/icon)](https://build.ros2.org/job/Rbin_uJ64__nlohmann_json_schema_validator_vendor__ubuntu_jammy_amd64__binary/9/)
```
00:03:01.563 -- Installing: /opt/ros/rolling/lib/libnlohmann_json_schema_validator.so.2.1.0
00:03:01.563 CMake Error at cmake_install.cmake:57 (file):
00:03:01.564   file INSTALL cannot copy file
00:03:01.564   "/tmp/binarydeb/ros-rolling-nlohmann-json-schema-validator-vendor-0.1.1/.obj-x86_64-linux-gnu/nlohmann_json_schema_validator/src/nlohmann_json_schema_validator-build/libnlohmann_json_schema_validator.so.2.1.0"
00:03:01.564   to "/opt/ros/rolling/lib/libnlohmann_json_schema_validator.so.2.1.0":
00:03:01.564   Permission denied.
00:03:01.564 
00:03:01.564 
00:03:01.564 make[5]: *** [Makefile:110: install] Error 1
```
It is failing because of the new CMakelist.txt install. It tries to install in the build process and has no permissions when building in Debian.
